Ast_def
wokron/tolangc pull request #8
Opened 2024-05-05 13:23 UTC by bohaocheung

Add abstract syntax tree's definition

2024-05-06 13:29 UTC, wokron commented
定义是不是应该放在头文件里？

2024-05-09 07:43 UTC, wokron commented on src/ast_def.cpp
> +};
这个父类型是否有必要？

2024-05-09 07:43 UTC, wokron commented on src/ast_def.cpp
> +    > variant;
是不是可以这样：
```cpp
using Stmt = std::variant<Get, Put, Tag, Let, If, To>;
```

2024-05-09 08:10 UTC, wokron requested changes
- 定义应该放在头文件中。
- 如果结构体只有一个属性，那么可以用 `using` 设置别名。
- `Node` 节点是否有意义？如果保留的话我认为也可以增加 `line` 属性表示行号。

2024-05-15 15:21 UTC, bohaocheung commented
已提交“语法树结构定义--V2”

2024-05-16 00:44 UTC, wokron approved these changes

2024-05-16 00:46 UTC, wokron commented
我又修改了一下，先合并了。不过 ast 的打印部分最好改成格式化的，比如说 json 格式。另外可以写一下测试。

2024-05-16 00:46 UTC, merged